Auto Invalidate changed files when merged to master

diff --git a/.github/workflows/sync-to-s3.yml b/.github/workflows/sync-to-s3.yml
--- a/.github/workflows/sync-to-s3.yml
+++ b/.github/workflows/sync-to-s3.yml
@@ -21,3 +21,32 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
           SOURCE_DIR: './'
+      - name: checkout dist
+        uses: actions/checkout@master
+        with:
+          ref: dist
+          # need at least 2 here so we can get a proper log in next step
+          fetch-depth: 2
+
+      - name: get updated files
+        run: |
+          # allow grep to fail
+          set +e
+          FILES=$(git log --stat="1000" -1 | grep '|' | awk '{print "/"$1}' | grep -e '\.html$')
+          set -e
+          [ -z "$FILES" ] && touch .updated_files && exit 0
+          for file in $FILES; do
+            echo $file
+            # add bare directory to list of updated paths when we see index.html
+            [[ "$file" == *"/index.html" ]] && echo $file | sed -e 's/\/index.html$/\//'
+          done | sort | uniq | tr '\n' ' ' > .updated_files
+
+      - name: invalidate
+        uses: chetan/invalidate-cloudfront-action@v2
+        env:
+          PATHS_FROM: .updated_files
+          AWS_REGION: 'us-east-2'
+          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          DEBUG: ${{ secrets.CLOUDFRONT_DEBUG }}
